### ISSUE TITLE
Newline after curly braces

### ISSUE THREAD

**Issue by drengr** [Mykhail/ACNS-CodeStyle#1]
First screenshot has an error, second hasn't.
![1](https://cloud.githubusercontent.com/assets/8355124/7495763/a1a3217e-f418-11e4-8fb7-ddc36db14a99.png)
![2](https://cloud.githubusercontent.com/assets/8355124/7495769/a84361a6-f418-11e4-9735-03adf8b5811e.png)

**Comment by Mykhail** [comment]
For fixing this issue were added exception to the rule "requirePaddingNewLinesAfterBlocks"

"requirePaddingNewLinesAfterBlocks": {
    "allExcept": ["inCallExpressions", "inArrayExpressions", "inProperties"]
}

You can get more information about this rule and exceptions <a href ="http://jscs.info/rule/requirePaddingNewLinesAfterBlocks.html">here</a>.

Thanks you for remarks!
