### ISSUE TITLE
CodeStyle suggestions

### ISSUE THREAD

**Issue by vodkin38** [Mykhail/ACNS-CodeStyle#2]
## Whitespace

> Use soft tabs set to 2 spaces.

Maybe we should use 4 spaces per tab ?
## Semicolons

```
// good
(function() {
  var name = 'Stark';
  return name;
})();

// good (guards against the function becoming an argument when two files with IIFEs are concatenated)
;(function() {
  var name = 'Stark';
  return name;
})();
```

Should we always use second option, just to be safe, or should we use either of them depending on a situation?
## Functions

What is the best practice when using function inside other functions like each/filter etc? For instance:

```
_.each(array, function(item) {
    console.log(item);
});
```

or

```
_.each(array, function(item) {
        console.log(item);
    }
);
```

or

```
_.each(array, 
    function(item) {
        console.log(item);
    }
);
```

or maybe some other way? Please advise on that, thank you.

**Comment by Mykhail** [comment]
<b>Whitespace</b> Your suggestion were approved on the DSM discussion. Currently we use 4 spaces per tab.

<b>Semicolons</b> This option should be considered as a recommendation. Feel free to use either of them depending on a situation.

<b>Functions</b> Related to approved code style first variant is the most correct:

<pre><code>_.each(array, function(item) {
    console.log(item);
});
</code></pre>

Thank you for your suggestions!
